### ISSUE TITLE
data prep checklist

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/archivesspace-development#41]
- [x] merge dsc2 containers into EAD
- [x] prepare containers file with locations
- [x] add default container profile "B"
- [x] prepare container profiles document
- [x] merge name variants, authfilenumbers into the EAD
- [x] remove partiality indicators from extent
- [x] normalize mudd extent
- [x] clarify whether we're submitting LAE data--yes, confirmed
- [x] make sure name ptrs are gone--handled by final transformation
- [x] remove commas from collection-level extent
- [x] remove @altrender from extent
- [x] check unittitle and xlink:title length one more time--max 1277 in unittitle; xlink:title was changed to boilerplate
-[ ] ~~what are we doing about "item" in extent? --asked Brian again for guidance -- this seems to be a local issue; moot for the ingest~~
- [x] remove empty elements (anywhere)
- [x] remove empty elements containing nothing but a head element
- [x] move container types from @unit into the value of the element (overwhelmingly necessary only for "digitalfiles" extent)
- [x] insert boilerplate "view digital content" on dao/xlink:title 
- [x] do we need to remove text from container? -- for the straightforward ones, yes; not possible in many (~30k) cases
- [x] remove "at least" from extent
- [x] check for presence of (non-empty) extent on the collection level
- [x] add @part to extent where more than one container type are present
- [x] remove emph from unittitles? anywhere? --yes
- [x] move containers to leaf components
- [x] remove NaN extents
- [x] check for "unknown" container types (change to unspecified per the documentation Brian sent)
- [x] regularize container types
- [x] add container types to extent where missing from text()
- [x] remove "more than" from extent
- [x] move cabinet, drawer to physloc
- [x] check for invalid dates
- [x] check for inverted dates
- [x] flip inverted dates
