### ISSUE TITLE
data prep checklist--pass 2

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/archivesspace-development#46]
CONTAINERS
- [x] merge dsc2 containers into EAD
- [x] prepare containers file with locations
- [x] remove text from container (where possible; let's see what happens with those where it's difficult)
- [x] move containers to leaf components if any have crept in
- [x] check for "unknown" container types (change to unspecified per the documentation Brian sent)
- [x] check that cabinet, drawer are moved to physloc

PROFILES
- [x] add default container profile "B"
- [x] prepare container profiles document

EXTENT
- [x] required at collection level
- [x] remove partiality, portions, approximately, at least, more than, circa, ca., c.  etc. indicators from extent
- [x] remove commas from collection-level extent
- [x] recompute @altrender and move to physdesc
- [x] make sure no new weirdly-formatted digital extents have crept in
- [x] move container types from @unit into the value of the element (overwhelmingly necessary only for "digitalfiles" extent)
- [x] remove NaN extents
- [x] extent must start with a number
- [x] extent must have a unit, i.e. must not end in a number

UNITTITLE/XLINK:TITLE
- [x] check unittitle and xlink:title length one more time--max 1277 in unittitle; xlink:title was changed to boilerplate
- [x] insert boilerplate "view digital content" on dao/xlink:title (if not already present)
- [x] remove emph from unittitles? anywhere? --yes

UNITDATE
- [x] check for invalid dates
- [x] check for inverted dates
- [x] flip inverted dates

OTHER
- [x] make sure name ptrs are gone--handled by final transformation
- [x] remove empty elements (anywhere)
- [x] remove empty elements containing nothing but a head element
- [x] check that every c has @level
